### TODO: 24 y 25
### Registro

POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "nombre": "nombre",
    "tel": "123456789",
    "email": "email1@gmail.com",
    "password": "Aa123456"
}


### Login

POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
    "email": "email1@gmail.com",
    "password": "Aa123456"
}


### Perfil

GET http://127.0.0.1:8000/api/users/me/
Cookie: session=b7cc60d55a4b3ca012e6bd453da7f3d7eb0cea9c


### Actualización perfil
PATCH http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Cookie: session=b7cc60d55a4b3ca012e6bd453da7f3d7eb0cea9c

{
    "nombre": "nombre nuevo",
    "tel": "123456789",
    "email": "email1@gmail.com",
    "password": "Aa123456"
}


### Logout
DELETE http://127.0.0.1:8000/api/users/logout/
Cookie: session=b7cc60d55a4b3ca012e6bd453da7f3d7eb0cea9c


### Baja
DELETE http://127.0.0.1:8000/api/users/me/
Cookie: session=b7cc60d55a4b3ca012e6bd453da7f3d7eb0cea9c
